os: linux
dist: jammy
language: node_js
env:
  - COREPACK_INTEGRITY_KEYS=0 # workaround for https://github.com/nodejs/corepack/issues/627
node_js:
  - 22
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run lint
  - pnpm run coverage
  - pnpm run build
deploy:
  provider: script
  script: bash scripts/deploy_npm_registry.sh
  on:
    tags: true
