language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run lint
  - pnpm run coverage
deploy:
  provider: npm
  api_token:
    secure: cGie5L9QnKwVzN7VJi5A6jhoNeLBSkMUK2muGzUjq8BJDmzpCqvQ1IZ4DN7vPlBXfKemhRblJ4OJqQ0YSKky7pPsrg4zr50THChMaSqxZ6UYp5mlH8wvcb66V4hoxGWklx2no4wy6D2vl42LGVNgtRbA8UmgNHXLMEb5t7lm2WZtPNioRjJbwdJquk+dMDiB8/RTSYmo2aLyaoicCCpcHNgWnFNaK/Gq6itSHwpS9tPt0/ocEnQCWglA85PdEriT4I/SXCFTC3kWZ7jadH4nUhvZ3pe9X5DrMDUBzOtf3yeg+4BUTr1qU1p+3rmWcJjAMswqh67+LN/o4b0/NkEiVKsvaTJVXRDfQ9PwwxT7usUjGj1tHsa7NSO5MtZCKoLqZuQVvYRxv3IxPpjYGCqCFrk3yJk8i5a7xFrj7PViQc0sVwg74473K5Xo6Y6IDxgXTKk/09Gfn2+ioimLdhluQU7VGVj+CSHVEEicOpgg6bZHtnx7ifTCes5vL1btffFmme5Eyy17AQUUC4TlBahIQWINkpO65C1MLMVZSkrT+0adH7290B+6DYLCRajjwkZDBhCR+QSV3HfdM7kxrgq2kU8QvlGU8eps0ZcO8M42aa1ck8S9UwwrtCDO4KAN2rPP6OlSvoYqMB5rFWuyQi5HVZRDfXsdjEVTWzv/K6s0X4o=
  on:
    tags: true
  edge: true