arch: amd64
os: linux
dist: noble
language: node_js
node_js:
  - 24
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run build
  - pnpm run lint
  - pnpm run coverage
deploy:
  provider: script
  script: bash scripts/deploy_npm_registry.sh
  on:
    tags: true
